### PR TITLE
Layout changes for the collector and storage using zipkin layout factory

### PR DESCRIPTION
**Pull request by zeagord**
Changing the build layout as per the Zipkin-Layout-Factory

### CODE REVIEW

**Comment by aliostad** [comment]
Sorry @adriancole do you have a minute to look at this? I am not that familiar with intricacies of maven.

**Comment by adriancole** [comment]
@aliostad new profile? or maybe didn't look in a while. nice shot. anyway got it covered.

**Comment by adriancole** [comment]
this is because the old layout was deprecated and made warnings. @zeagord made a defensive copy so we aren't broke when we upgrade

**Comment by aliostad** [comment]
Nice, thanks! 👍 
Yeah the profile picture was taken at work for the mugshot. Better than previous :)

**Pull request merged**
